networks:
  app_network:
    driver: bridge

services:
  mc:
    image: itzg/minecraft-server:java8
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: 1.7.10
      ONLINE_MODE: false
      MEMORY: 3G
      RCON_PASSWORD: "changethis!"
    networks:
      - app_network
    volumes:
      - mcdata:/data

  web:
    image: itzg/rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: mc
      RWA_RCON_PASSWORD: "changethis!"
    networks:
      - app_network
    ports:
      - "4326:4326"
      - "4327:4327"

volumes:
  mcdata: